export type ProductCategory = "integrales" | "keto";
export type ProductSubcategory = "saladas" | "dulces";


export type Product = {
  id: number;
  name: string;
  category: ProductCategory;
  subcategory: ProductSubcategory;
  price: number;
  isActive?: boolean;
  description: string;
  images: string[];
};

export const PRODUCTS: Product[] = [
  { id: 1, name: "Bases para tartas individuales (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Bases crujientes y livianas de harina integral. Ideales para armar tus propias tartas saladas en casa.", images: ["/images/Base%20para%20Tartas%20Individuales%20integrales%20-1%20(6).jpg"] },
  { id: 2, name: "Chips (x12)", category: "integrales", subcategory: "saladas", price: 9000, description: "Pequeños chips de pan integral, suaves por dentro y doraditos por fuera. El bocado perfecto para tus picadas.", images: ["/images/Chips%20Integrales%20(12).png"] },
  { id: 3, name: "Chips rellenos de JyQ (x12)", category: "integrales", subcategory: "saladas", price: 10000, description: "Clásicos chips integrales rellenos con abundante jamón y queso. Un éxito asegurado en cualquier reunión.", images: ["/images/chips-rellenos-jyq-integrales.jpg"] },
  { id: 4, name: "Chips rellenos de caprese (x12)", category: "integrales", subcategory: "saladas", price: 10000, description: "El sabor de Italia en pequeños panes integrales rellenos de queso, tomate y albahaca fresca.", images: ["/images/chips-integrales-caprese%20(12).jpg"] },
  { id: 5, name: "Crackers con semillas (250g)", category: "integrales", subcategory: "saladas", price: 6000, description: "Crujientes y livianas, con una mezcla de semillas que aportan sabor y nutrientes. Ideales para acompañar quesos.", images: ["/images/CRACKERS-INTEGRALES-1.jpeg"] },
  { id: 6, name: "Crutones (250g)", category: "integrales", subcategory: "saladas", price: 4000, description: "Trocitos de pan integral tostados y sazonados. El toque crocante que tus sopas y ensaladas necesitan.", images: ["/images/crutones1.png"] },
  { id: 7, name: "Focaccia con Cherry y Aceituna (grande)", category: "integrales", subcategory: "saladas", price: 9000, description: "Esponjosa focaccia integral cubierta con jugosos tomates cherry y aceitunas. Un festín de sabores mediterráneos.", images: ["/images/focaccia2.png"] },
  { id: 8, name: "Focaccia con Cherry y Aceituna (chica)", category: "integrales", subcategory: "saladas", price: 6000, description: "Esponjosa focaccia integral cubierta con jugosos tomates cherry y aceitunas, en formato individual.", images: ["/images/focaccia.png"] },
  { id: 9, name: "Hamburguesas Legumbres (x6)", category: "integrales", subcategory: "saladas", price: 8500, description: "Sabrosas y nutritivas hamburguesas a base de legumbres. Una alternativa vegetal llena de proteínas y sabor.", images: ["/images/HAMBURGUESA-LEGUMBRES.png"] },
  { id: 10, name: "Pan de Nuez grande (900g)", category: "integrales", subcategory: "saladas", price: 7000, description: "Un pan rústico e imponente, con el toque crujiente y el sabor inconfundible de las nueces.", images: ["/images/pan-nuez-1.jpg", "/images/pan-nuez2.jpg"] },
  { id: 11, name: "Pan Integral grande con semillas (900g)", category: "integrales", subcategory: "saladas", price: 6000, description: "El infaltable pan de molde integral, cubierto de semillas crujientes. Perfecto para tus tostadas de cada mañana.", images: ["/images/PAN-INTEGRAL-GRANDE.jpeg"] },
  { id: 12, name: "Pan saborizado chico (x12)", category: "integrales", subcategory: "saladas", price: 8000, description: "Pancitos saborizados con hierbas y especias. Ideales para armar los sandwiches más sabrosos.", images: ["/images/Panes%20Saborizados%20Chicos%20(12).jpg"] },
  { id: 13, name: "Pan tortuga mediano (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "El clásico pan de hamburguesa en su versión integral, tierno y perfecto para tus preparaciones caseras.", images: ["/images/Pan%20Tortuga%20Mediano%20(6).jpg"] },
  { id: 14, name: "Pan árabe (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Liviano y flexible pan pita integral. Ideal para rellenar, tostar o disfrutar con tus dips favoritos.", images: ["/images/pan-arabe-integral-1%20(6).jpg"] },
  { id: 15, name: "Pizzetas (x12)", category: "integrales", subcategory: "saladas", price: 12000, description: "Bases de pizzeta integrales listas para llevar al horno con el queso y los toppings que prefieras.", images: ["/images/PIZZETAS-INTEGRALES.png"] },
  { id: 16, name: "Scones de Queso (x8)", category: "integrales", subcategory: "saladas", price: 6000, description: "Scones doraditos por fuera y tiernos por dentro, con un intenso y tentador sabor a queso.", images: ["/images/scones-queso1.jpg", "/images/Scones%20de%20Queso-2%20(8).jpg"] },
  { id: 17, name: "Tapa para tacos/fajitas (x6)", category: "integrales", subcategory: "saladas", price: 7000, description: "Tortillas integrales flexibles y resistentes. La base perfecta para tus tacos y burritos saludables.", images: ["/images/fajitas.png"] },
  { id: 18, name: "Tartas individuales", category: "integrales", subcategory: "saladas", price: 6500, description: "Disfrutá nuestras tartas individuales con una base de harina integral y una variedad de sabores: calabaza con choclo y jamón / jamón y queso / cebolla y queso / verdura / caprese / cebolla caramelizada / roquefort. Cada opción está hecha con ingredientes frescos para ofrecerte una experiencia deliciosa y satisfactoria.", images: ["/images/TARTAS-INDIVIDUALES-INTEGRAL.jpg"] },

  { id: 19, name: "Bon o Bon saludable (x4)", category: "integrales", subcategory: "dulces", price: 6500, description: "La versión saludable del clásico bocado, con un corazón cremoso y una cobertura de chocolate irresistible.", images: ["/images/bonobon.jpg", "/images/bon-o-bon-saludable%284%29.jpg"] },
  { id: 20, name: "Brownie saludable (1 porción)", category: "integrales", subcategory: "dulces", price: 4000, description: "Húmedo, intensamente chocolatoso y elaborado con harinas integrales. La merienda perfecta sin renunciar al placer.", images: ["/images/BROWNIE-PORCION.png"] },
  { id: 21, name: "Budín de Manzana (450g)", category: "integrales", subcategory: "dulces", price: 8000, description: "Esponjoso y aromático, elaborado con manzanas frescas y un toque de canela que enamora en cada bocado.", images: ["/images/budin-manzana1.jpg", "/images/budin-manzana2.jpg"] },
  { id: 22, name: "Carrot Cake", category: "integrales", subcategory: "dulces", price: 8000, description: "Torta de zanahoria húmeda, perfumada con especias y con una textura increíble. Un clásico renovado.", images: ["/images/carrot cake.png"] },
  { id: 23, name: "Muffins de Mandarina (x6)", category: "integrales", subcategory: "dulces", price: 8000, description: "Muffins tiernos y perfumados con el cítrico y fresco sabor de la mandarina. Ideales para el mate de la tarde.", images: ["/images/Muffins%20de%20Mandarina%201%20%286%29.png", "/images/Muffins%20de%20Mandarina%20%286%29.png"] },
  { id: 24, name: "Pancakes (x4)", category: "integrales", subcategory: "dulces", price: 5000, description: "Panqueques integrales listos para acompañar con miel, frutas o dulce de leche. Tu desayuno de campeones.", images: ["/images/Pancakes%201%20%284%29.jpg", "/images/Pancakes%202%20%284%29.jpg", "/images/Pancakes%20%284%29.jpg"] },
  { id: 25, name: "Pastafrola individual (x1) (Memb./Bat./Ricot.)", category: "integrales", subcategory: "dulces", price: 7000, description: "Nuestra clásica pastafrola en formato individual, con masa integral y tu relleno favorito. Puro sabor a tradición.", images: ["/images/PASTAFROLAS-1.png"] },
  { id: 26, name: "Pepas de Membrillo y Batata (x12)", category: "integrales", subcategory: "dulces", price: 10000, description: "Las infaltables galletitas con centro de membrillo o batata. Perfectas para acompañar cada infusión del día.", images: ["/images/Pepas-integrales%20%2812%29.jpg"] },
  { id: 28, name: "Nueces rellenas de DDL bañadas en choc. (x6)", category: "integrales", subcategory: "dulces", price: 7000, description: "Nueces crujientes rellenas de abundante dulce de leche y bañadas en chocolate. Un capricho irresistible.", images: ["/images/nueces-ddl-keto-integral.jpg"] },

  { id: 29, name: "Bases para tartas keto (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Bases bajas en carbohidratos para preparar tus tartas. Ligeras y perfectas para tu dieta cetogénica.", images: ["/images/Base%20para%20Tarta%20Keto%20%283%20o%206%29.jpg"] },
  { id: 30, name: "Bases para tartas keto (x6)", category: "keto", subcategory: "saladas", price: 9000, description: "Pack de bases bajas en carbohidratos para tartas caseras. La solución práctica para tus comidas semanales.", images: ["/images/Base%20para%20Tarta%20Keto%20%283%20o%206%29.jpg"] },
  { id: 31, name: "Chips rellenos de JyQ (x6)", category: "keto", subcategory: "saladas", price: 10000, description: "Pancitos keto súper esponjosos rellenos de jamón y queso. El bocado perfecto, sin harinas refinadas.", images: ["/images/family-crackers-chips.png"] },
  { id: 32, name: "Chips rellenos de JyQ (x12)", category: "keto", subcategory: "saladas", price: 15000, description: "Pancitos keto súper esponjosos rellenos de jamón y queso, en cantidad ideal para compartir.", images: ["/images/family-crackers-chips.png"] },
  { id: 33, name: "Crackers con semillas (250g)", category: "keto", subcategory: "saladas", price: 7000, description: "Galletas saladas crujientes a base de semillas, ideales para untar y acompañar tus picadas keto.", images: ["/images/CRACKERS-1.jpg", "/images/CRACKERS-2.jpg"] },
  { id: 34, name: "Tapa/Fajitas para tacos (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Tortillas keto flexibles y de gran sabor. Perfectas para armar burritos o tacos bajos en carbohidratos.", images: ["/images/Tapa-Fajitas%20Keto%20(3%20o%206).jpeg"] },
  { id: 35, name: "Tapa/Fajitas para tacos (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Pack de tortillas keto flexibles, indispensables para una cena de tacos deliciosa y saludable.", images: ["/images/Tapa-Fajitas%20Keto%20(3%20o%206).jpeg"] },
  { id: 36, name: "Figacitas (x8)", category: "keto", subcategory: "saladas", price: 9000, description: "Pequeños panes suaves y tiernos aptos keto. Ideales para preparar minisandwiches para toda la familia.", images: ["/images/FIGACITAS-KETO.jpg"] },
  { id: 37, name: "Muffins de Queso (x6)", category: "keto", subcategory: "saladas", price: 9000, description: "Muffins salados, húmedos y con un intenso sabor a queso. Una excelente opción keto para desayunar o merendar.", images: ["/images/Muffins%20de%20Queso.jpg"] },
  { id: 38, name: "Pan árabe (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Clásico pan de estilo árabe, chato y apto keto. Ideal para rellenar o acompañar con dips.", images: ["/images/pan-arabe-integral-1%20%286%29.jpg"] },
  { id: 39, name: "Pan árabe (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Clásico pan de estilo árabe, chato y apto keto. Ideal para tus comidas bajas en hidratos.", images: ["/images/pan-arabe-integral-1%20%286%29.jpg"] },
  { id: 40, name: "Ñoquis Calabaza o Espinaca (500g)", category: "keto", subcategory: "saladas", price: 15000, description: "Exquisitos ñoquis sin harinas refinadas. Saborizados con calabaza o espinaca, un plato principal nutritivo y keto.", images: ["/images/ÑOQUIS-500g.jpg"] },
  { id: 41, name: "Pan de Almendras (700g)", category: "keto", subcategory: "saladas", price: 8500, description: "Un pan de molde keto elaborado a base de almendras, de miga tierna y sabor suave, perfecto para tus tostadas.", images: ["/images/panAlmendras.jpeg"] },
  { id: 42, name: "Pan tortuga (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Esponjosos panes redondos aptos keto. La base ideal para preparar increíbles hamburguesas saludables.", images: ["/images/pan-tortuga-keto.png"] },
  { id: 43, name: "Pizzetas (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Bases keto para mini pizzas, con la textura justa para agregar tu salsa y queso favorito.", images: ["/images/pizzetas-keto-scaled.jpg"] },
  { id: 44, name: "Scones de Queso (x8)", category: "keto", subcategory: "saladas", price: 7000, description: "Sabrosos scones con queso, de miga desgranable. Una alternativa keto salada que nunca falla.", images: ["/images/Scons-queso-keto.jpg"] },
  { id: 45, name: "Tartas individuales", category: "keto", subcategory: "saladas", price: 7500, description: "Mini tartas deliciosas con base baja en carbohidratos y rellenos variados. Un almuerzo exprés y saludable.", images: ["/images/TARTAS-INDIVIDUALES-KETO.jpg"] },

  { id: 46, name: "Alfajor relleno de DDL s/azúcar o ganache de chocolate s/azúcar (x1)", category: "keto", subcategory: "dulces", price: 3500, description: "Delicado alfajor de masa suave con abundante relleno keto, sin azúcar. Un mimo dulce irresistible.", images: ["/images/alfajor-relleno-ddl-ganache.jpg", "/images/alfajor-keto-sin-bano-de-chocolate-scaled.jpg"] },
  { id: 47, name: "Alfajor bañado en chocolate relleno de DDL o ganache de chocolate s/azúcar (x1)", category: "keto", subcategory: "dulces", price: 4000, description: "Exquisito alfajor bañado, con interior cremoso y una cobertura crujiente. Todo el sabor, cero culpas.", images: ["/images/alfajor-chocolate-ganache-scaled.jpg"] },
  { id: 48, name: "Bombón keto de chocolate relleno de DDL o DDL de arándanos (x6)", category: "keto", subcategory: "dulces", price: 7000, description: "Pequeñas delicias de chocolate intenso con corazón dulce y frutal. Perfectos para un antojo keto.", images: ["/images/bombon-keto-1-scaled.jpg", "/images/bombon-keto-scaled-2.jpg"] },
  { id: 49, name: "Bon o Bon saludable (x4)", category: "keto", subcategory: "dulces", price: 7000, description: "Crujiente y cremoso bocadito apto keto. Una versión saludable de la golosina que todos aman.", images: ["/images/bonobon.jpg", "/images/bon-o-bon-saludable%284%29.jpg"] },
  { id: 50, name: "Brownie (por porción)", category: "keto", subcategory: "dulces", price: 4500, description: "Cuadrado de brownie húmedo y de sabor profundo a cacao. Una indulgencia cetogénica que se derrite en la boca.", images: ["/images/BROWNIE-PORCION.png"] },
  { id: 51, name: "Budín con Nuez", category: "keto", subcategory: "dulces", price: 9000, description: "Budín keto suave con trozos de nuez que le dan una textura increíble. Ideal para el café de la tarde.", images: ["/images/BUDIN-CON-NUEZ-KETO-1.jpeg", "/images/BUDIN-CON-NUEZ-KETO.jpeg"] },
  { id: 52, name: "Budín de Limón y Coco (ganache choc. blanco)", category: "keto", subcategory: "dulces", price: 9000, description: "Refrescante budín keto de limón con toques de coco y una exquisita ganache superior.", images: ["/images/budin-de-limon-scaled.jpg"] },
  { id: 53, name: "Mantecol saludable (170g)", category: "keto", subcategory: "dulces", price: 7000, description: "El clásico turrón de maní adaptado para tu dieta baja en carbohidratos, con su textura desmenuzable característica.", images: ["/images/MANTECOL-1.jpg", "/images/MANTECOL-2.jpg", "/images/MANTECOL-3.jpg"] },
  { id: 54, name: "Muffins de Nueces o Arándanos o Chocolate (x6)", category: "keto", subcategory: "dulces", price: 9000, description: "Muffins dulces, esponjosos y en diferentes variedades. Una merienda keto con mucho sabor.", images: ["/images/muffins-arandanos-1.jpg", "/images/muffins-chocolate-1.jpg", "/images/muffins-chocolate-keto-2.jpg", "/images/muffinNuezKeto.jpg"] },
  { id: 55, name: "Muffins rellenos con ganache (x6)", category: "keto", subcategory: "dulces", price: 9500, description: "Tiernos muffins keto con un corazón fluido y tentador de ganache. Una delicia para paladares exigentes.", images: ["/images/MUFFINS-REELENO-GANACHE.jpg"] },
  { id: 56, name: "Pancakes (x4)", category: "keto", subcategory: "dulces", price: 7500, description: "Pancakes keto, suaves y esponjosos. Listos para apilar y servir con tus siropes sin azúcar.", images: ["/images/Pancakes%201%20%284%29.jpg", "/images/Pancakes%202%20%284%29.jpg", "/images/Pancakes%20%284%29.jpg"] },
  { id: 57, name: "Pan Dulce (350g)", category: "keto", subcategory: "dulces", price: 12000, description: "El pan de las fiestas en versión baja en carbohidratos, tierno y con el mismo aroma a celebración.", images: ["/images/pan-dulce-keto1.jpg", "/images/pan-dulce-keto2.jpg", "/images/pan-dulce-keto3.png"] },
  { id: 58, name: "Pepas de DDL s/azúcar (x12)", category: "keto", subcategory: "dulces", price: 12000, description: "Las tradicionales galletitas con una generosa gota de dulce de leche keto en el centro. Insuperables.", images: ["/images/pepas-ddl-keto-x12.jpg"] },
  { id: 59, name: "Rogel keto (1200g/1300g)", category: "keto", subcategory: "dulces", price: 35000, description: "Un espectacular Rogel en capas, repleto de dulce de leche sin azúcar y merengue. La torta estrella para compartir.", images: ["/images/rogel-keto1-scaled.jpg", "/images/rogel-keto-scaled.jpg"] },
  { id: 60, name: "Mini rogel tipo alfajor bañado en choco.", category: "keto", subcategory: "dulces", price: 5000, description: "La magia del rogel en porción individual, con baño de chocolate amargo para darle un toque especial.", images: ["/images/MINIrogel.jpg"] },
  { id: 61, name: "Mini rogel sin baño", category: "keto", subcategory: "dulces", price: 4500, description: "Porción individual de rogel keto clásico, con capas crujientes y mucho dulce de leche.", images: ["/images/MINIrogel.jpg"] },
  { id: 62, name: "Tarta de coco individual", category: "keto", subcategory: "dulces", price: 10000, description: "Tartita crujiente con base keto, generosa capa de dulce de leche y un irresistible topping de coco rallado.", images: ["/images/TARTA-COCO-INDIVIDUAL-KETO.jpg"] },
];
