export type ProductCategory = "integrales" | "keto";
export type ProductSubcategory = "saladas" | "dulces";

export type Product = {
  id: number;
  name: string;
  category: ProductCategory;
  subcategory: ProductSubcategory;
  price: number;
  isActive?: boolean;
  description: string;
  image: string;
};

export const PRODUCTS: Product[] = [
  { id: 1, name: "Bases para tartas individuales (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Bases crujientes y livianas de harina integral. Ideales para armar tus propias tartas saladas en casa.", image: "/images/family-tartas-pizzetas.png" },
  { id: 2, name: "Chips (x12)", category: "integrales", subcategory: "saladas", price: 9000, description: "Pequeños chips de pan integral, suaves por dentro y doraditos por fuera. El bocado perfecto para tus picadas.", image: "/images/family-crackers-chips.png" },
  { id: 3, name: "Chips rellenos de JyQ (x12)", category: "integrales", subcategory: "saladas", price: 10000, description: "Clásicos chips integrales rellenos con abundante jamón y queso. Un éxito asegurado en cualquier reunión.", image: "/images/family-crackers-chips.png" },
  { id: 4, name: "Chips rellenos de caprese (x12)", category: "integrales", subcategory: "saladas", price: 10000, description: "El sabor de Italia en pequeños panes integrales rellenos de queso, tomate y albahaca fresca.", image: "/images/family-crackers-chips.png" },
  { id: 5, name: "Crackers con semillas (250g)", category: "integrales", subcategory: "saladas", price: 6000, description: "Crujientes y livianas, con una mezcla de semillas que aportan sabor y nutrientes. Ideales para acompañar quesos.", image: "/images/family-crackers-chips.png" },
  { id: 6, name: "Crutones (250g)", category: "integrales", subcategory: "saladas", price: 4000, description: "Trocitos de pan integral tostados y sazonados. El toque crocante que tus sopas y ensaladas necesitan.", image: "/images/family-crackers-chips.png" },
  { id: 7, name: "Focaccia con Cherry y Aceituna (grande)", category: "integrales", subcategory: "saladas", price: 9000, description: "Esponjosa focaccia integral cubierta con jugosos tomates cherry y aceitunas. Un festín de sabores mediterráneos.", image: "/images/family-panes-integrales.png" },
  { id: 8, name: "Focaccia con Cherry y Aceituna (chica)", category: "integrales", subcategory: "saladas", price: 6000, description: "Esponjosa focaccia integral cubierta con jugosos tomates cherry y aceitunas, en formato individual.", image: "/images/family-panes-integrales.png" },
  { id: 9, name: "Hamburguesas Legumbres (x6)", category: "integrales", subcategory: "saladas", price: 8500, description: "Sabrosas y nutritivas hamburguesas a base de legumbres. Una alternativa vegetal llena de proteínas y sabor.", image: "/images/family-panes-integrales.png" },
  { id: 10, name: "Pan de Nuez grande (900g)", category: "integrales", subcategory: "saladas", price: 7000, description: "Un pan rústico e imponente, con el toque crujiente y el sabor inconfundible de las nueces.", image: "/images/family-panes-integrales.png" },
  { id: 63, name: "Pan de Harina de Garbanzo (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Tiernos pancitos elaborados con harina de garbanzo, ricos en fibra y con un sabor deliciosamente único.", image: "/images/family-panes-integrales.png" },
  { id: 11, name: "Pan Integral grande con semillas (900g)", category: "integrales", subcategory: "saladas", price: 6000, description: "El infaltable pan de molde integral, cubierto de semillas crujientes. Perfecto para tus tostadas de cada mañana.", image: "/images/family-panes-integrales.png" },
  { id: 12, name: "Pan saborizado chico (x12)", category: "integrales", subcategory: "saladas", price: 8000, description: "Pancitos saborizados con hierbas y especias. Ideales para armar los sandwiches más sabrosos.", image: "/images/family-panes-integrales.png" },
  { id: 13, name: "Pan tortuga mediano (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "El clásico pan de hamburguesa en su versión integral, tierno y perfecto para tus preparaciones caseras.", image: "/images/family-panes-integrales.png" },
  { id: 14, name: "Pan árabe (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Liviano y flexible pan pita integral. Ideal para rellenar, tostar o disfrutar con tus dips favoritos.", image: "/images/family-panes-integrales.png" },
  { id: 15, name: "Pizzetas (x12)", category: "integrales", subcategory: "saladas", price: 12000, description: "Bases de pizzeta integrales listas para llevar al horno con el queso y los toppings que prefieras.", image: "/images/family-tartas-pizzetas.png" },
  { id: 16, name: "Scones de Queso (x8)", category: "integrales", subcategory: "saladas", price: 6000, description: "Scones doraditos por fuera y tiernos por dentro, con un intenso y tentador sabor a queso.", image: "/images/family-muffins-scones.png" },
  { id: 17, name: "Tapa para tacos/fajitas (x6)", category: "integrales", subcategory: "saladas", price: 7000, description: "Tortillas integrales flexibles y resistentes. La base perfecta para tus tacos y burritos saludables.", image: "/images/family-tartas-pizzetas.png" },
  { id: 18, name: "Tartas individuales", category: "integrales", subcategory: "saladas", price: 6500, description: "Deliciosas tartitas con masa integral y rellenos caseros llenos de sabor. Un almuerzo práctico y nutritivo.", image: "/images/family-tartas-pizzetas.png" },

  { id: 19, name: "Bon o Bon saludable (x4)", category: "integrales", subcategory: "dulces", price: 6500, description: "La versión saludable del clásico bocado, con un corazón cremoso y una cobertura de chocolate irresistible.", image: "/images/family-trufas-bombones.png" },
  { id: 20, name: "Brownie saludable (1 porción)", category: "integrales", subcategory: "dulces", price: 4000, description: "Húmedo, intensamente chocolatoso y elaborado con harinas integrales. La merienda perfecta sin renunciar al placer.", image: "/images/family-brownies-budines.png" },
  { id: 21, name: "Budín de Manzana (450g)", category: "integrales", subcategory: "dulces", price: 8000, description: "Esponjoso y aromático, elaborado con manzanas frescas y un toque de canela que enamora en cada bocado.", image: "/images/family-brownies-budines.png" },
  { id: 22, name: "Carrot Cake", category: "integrales", subcategory: "dulces", price: 8000, description: "Torta de zanahoria húmeda, perfumada con especias y con una textura increíble. Un clásico renovado.", image: "/images/family-brownies-budines.png" },
  { id: 23, name: "Muffins de Mandarina (x6)", category: "integrales", subcategory: "dulces", price: 8000, description: "Muffins tiernos y perfumados con el cítrico y fresco sabor de la mandarina. Ideales para el mate de la tarde.", image: "/images/family-muffins-scones.png" },
  { id: 24, name: "Pancakes (x4)", category: "integrales", subcategory: "dulces", price: 5000, description: "Panqueques integrales listos para acompañar con miel, frutas o dulce de leche. Tu desayuno de campeones.", image: "/images/family-pancakes.png" },
  { id: 25, name: "Pastafrola individual (x1) (Memb./Bat./Ricot.)", category: "integrales", subcategory: "dulces", price: 7000, description: "Nuestra clásica pastafrola en formato individual, con masa integral y tu relleno favorito. Puro sabor a tradición.", image: "/images/family-alfajores-pepas.png" },
  { id: 26, name: "Pepas de Membrillo y Batata (x12)", category: "integrales", subcategory: "dulces", price: 10000, description: "Las infaltables galletitas con centro de membrillo o batata. Perfectas para acompañar cada infusión del día.", image: "/images/family-alfajores-pepas.png" },
  { id: 27, name: "Trufas de chocolate s/azúcar (x4)", category: "integrales", subcategory: "dulces", price: 6000, description: "Bocados intensos de chocolate amargo, sin azúcar agregada. Un mimo saludable para los amantes del cacao.", image: "/images/family-trufas-bombones.png" },
  { id: 28, name: "Nueces rellenas de DDL bañadas en choc. (x6)", category: "integrales", subcategory: "dulces", price: 7000, description: "Nueces crujientes rellenas de abundante dulce de leche y bañadas en chocolate. Un capricho irresistible.", image: "/images/family-trufas-bombones.png" },

  { id: 29, name: "Bases para tartas keto (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Bases bajas en carbohidratos para preparar tus tartas. Ligeras y perfectas para tu dieta cetogénica.", image: "/images/family-tartas-pizzetas.png" },
  { id: 30, name: "Bases para tartas keto (x6)", category: "keto", subcategory: "saladas", price: 9000, description: "Pack de bases bajas en carbohidratos para tartas caseras. La solución práctica para tus comidas semanales.", image: "/images/family-tartas-pizzetas.png" },
  { id: 31, name: "Chips rellenos de JyQ (x6)", category: "keto", subcategory: "saladas", price: 10000, description: "Pancitos keto súper esponjosos rellenos de jamón y queso. El bocado perfecto, sin harinas refinadas.", image: "/images/family-crackers-chips.png" },
  { id: 32, name: "Chips rellenos de JyQ (x12)", category: "keto", subcategory: "saladas", price: 15000, description: "Pancitos keto súper esponjosos rellenos de jamón y queso, en cantidad ideal para compartir.", image: "/images/family-crackers-chips.png" },
  { id: 33, name: "Crackers con semillas (250g)", category: "keto", subcategory: "saladas", price: 7000, description: "Galletas saladas crujientes a base de semillas, ideales para untar y acompañar tus picadas keto.", image: "/images/family-crackers-chips.png" },
  { id: 34, name: "Tapa/Fajitas para tacos (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Tortillas keto flexibles y de gran sabor. Perfectas para armar burritos o tacos bajos en carbohidratos.", image: "/images/family-tartas-pizzetas.png" },
  { id: 35, name: "Tapa/Fajitas para tacos (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Pack de tortillas keto flexibles, indispensables para una cena de tacos deliciosa y saludable.", image: "/images/family-tartas-pizzetas.png" },
  { id: 36, name: "Figacitas (x8)", category: "keto", subcategory: "saladas", price: 9000, description: "Pequeños panes suaves y tiernos aptos keto. Ideales para preparar minisandwiches para toda la familia.", image: "/images/family-panes-keto.png" },
  { id: 37, name: "Muffins de Queso (x6)", category: "keto", subcategory: "saladas", price: 9000, description: "Muffins salados, húmedos y con un intenso sabor a queso. Una excelente opción keto para desayunar o merendar.", image: "/images/family-muffins-scones.png" },
  { id: 38, name: "Pan árabe (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Clásico pan de estilo árabe, chato y apto keto. Ideal para rellenar o acompañar con dips.", image: "/images/family-panes-keto.png" },
  { id: 39, name: "Pan árabe (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Clásico pan de estilo árabe, chato y apto keto. Ideal para tus comidas bajas en hidratos.", image: "/images/family-panes-keto.png" },
  { id: 40, name: "Ñoquis Calabaza o Espinaca (500g)", category: "keto", subcategory: "saladas", price: 15000, description: "Exquisitos ñoquis sin harinas refinadas. Saborizados con calabaza o espinaca, un plato principal nutritivo y keto.", image: "/images/family-noquis.png" },
  { id: 41, name: "Pan de Almendras (700g)", category: "keto", subcategory: "saladas", price: 8500, description: "Un pan de molde keto elaborado a base de almendras, de miga tierna y sabor suave, perfecto para tus tostadas.", image: "/images/family-panes-keto.png" },
  { id: 42, name: "Pan tortuga (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Esponjosos panes redondos aptos keto. La base ideal para preparar increíbles hamburguesas saludables.", image: "/images/family-panes-keto.png" },
  { id: 43, name: "Pizzetas (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Bases keto para mini pizzas, con la textura justa para agregar tu salsa y queso favorito.", image: "/images/family-tartas-pizzetas.png" },
  { id: 44, name: "Scones de Queso (x8)", category: "keto", subcategory: "saladas", price: 7000, description: "Sabrosos scones con queso, de miga desgranable. Una alternativa keto salada que nunca falla.", image: "/images/family-muffins-scones.png" },
  { id: 45, name: "Tartas individuales", category: "keto", subcategory: "saladas", price: 7500, description: "Mini tartas deliciosas con base baja en carbohidratos y rellenos variados. Un almuerzo exprés y saludable.", image: "/images/family-tartas-pizzetas.png" },

  { id: 46, name: "Alfajor relleno de DDL s/azúcar o ganache de chocolate s/azúcar (x1)", category: "keto", subcategory: "dulces", price: 3500, description: "Delicado alfajor de masa suave con abundante relleno keto, sin azúcar. Un mimo dulce irresistible.", image: "/images/family-alfajores-pepas.png" },
  { id: 47, name: "Alfajor bañado en chocolate relleno de DDL o ganache de chocolate s/azúcar (x1)", category: "keto", subcategory: "dulces", price: 4000, description: "Exquisito alfajor bañado, con interior cremoso y una cobertura crujiente. Todo el sabor, cero culpas.", image: "/images/family-alfajores-pepas.png" },
  { id: 48, name: "Bombón keto de chocolate relleno de DDL o DDL de arándanos (x6)", category: "keto", subcategory: "dulces", price: 7000, description: "Pequeñas delicias de chocolate intenso con corazón dulce y frutal. Perfectos para un antojo keto.", image: "/images/family-trufas-bombones.png" },
  { id: 49, name: "Bon o Bon saludable (x4)", category: "keto", subcategory: "dulces", price: 7000, description: "Crujiente y cremoso bocadito apto keto. Una versión saludable de la golosina que todos aman.", image: "/images/family-trufas-bombones.png" },
  { id: 50, name: "Brownie (por porción)", category: "keto", subcategory: "dulces", price: 4500, description: "Cuadrado de brownie húmedo y de sabor profundo a cacao. Una indulgencia cetogénica que se derrite en la boca.", image: "/images/family-brownies-budines.png" },
  { id: 51, name: "Budín con Nuez", category: "keto", subcategory: "dulces", price: 9000, description: "Budín keto suave con trozos de nuez que le dan una textura increíble. Ideal para el café de la tarde.", image: "/images/family-brownies-budines.png" },
  { id: 52, name: "Budín de Limón y Coco (ganache choc. blanco)", category: "keto", subcategory: "dulces", price: 9000, description: "Refrescante budín keto de limón con toques de coco y una exquisita ganache superior.", image: "/images/family-brownies-budines.png" },
  { id: 53, name: "Mantecol saludable (170g)", category: "keto", subcategory: "dulces", price: 7000, description: "El clásico turrón de maní adaptado para tu dieta baja en carbohidratos, con su textura desmenuzable característica.", image: "/images/family-brownies-budines.png" },
  { id: 54, name: "Muffins de Nueces o Arándanos o Chocolate (x6)", category: "keto", subcategory: "dulces", price: 9000, description: "Muffins dulces, esponjosos y en diferentes variedades. Una merienda keto con mucho sabor.", image: "/images/family-muffins-scones.png" },
  { id: 55, name: "Muffins rellenos con ganache (x6)", category: "keto", subcategory: "dulces", price: 9500, description: "Tiernos muffins keto con un corazón fluido y tentador de ganache. Una delicia para paladares exigentes.", image: "/images/family-muffins-scones.png" },
  { id: 56, name: "Pancakes (x4)", category: "keto", subcategory: "dulces", price: 7500, description: "Pancakes keto, suaves y esponjosos. Listos para apilar y servir con tus siropes sin azúcar.", image: "/images/family-pancakes.png" },
  { id: 57, name: "Pan Dulce (350g)", category: "keto", subcategory: "dulces", price: 12000, description: "El pan de las fiestas en versión baja en carbohidratos, tierno y con el mismo aroma a celebración.", image: "/images/family-brownies-budines.png" },
  { id: 58, name: "Pepas de DDL s/azúcar (x12)", category: "keto", subcategory: "dulces", price: 12000, description: "Las tradicionales galletitas con una generosa gota de dulce de leche keto en el centro. Insuperables.", image: "/images/family-alfajores-pepas.png" },
  { id: 59, name: "Rogel keto (1200g/1300g)", category: "keto", subcategory: "dulces", price: 35000, description: "Un espectacular Rogel en capas, repleto de dulce de leche sin azúcar y merengue. La torta estrella para compartir.", image: "/images/family-brownies-budines.png" },
  { id: 60, name: "Mini rogel tipo alfajor bañado en choco.", category: "keto", subcategory: "dulces", price: 5000, description: "La magia del rogel en porción individual, con baño de chocolate amargo para darle un toque especial.", image: "/images/family-alfajores-pepas.png" },
  { id: 61, name: "Mini rogel sin baño", category: "keto", subcategory: "dulces", price: 4500, description: "Porción individual de rogel keto clásico, con capas crujientes y mucho dulce de leche.", image: "/images/family-alfajores-pepas.png" },
  { id: 62, name: "Tarta de coco individual", category: "keto", subcategory: "dulces", price: 10000, description: "Tartita crujiente con base keto, generosa capa de dulce de leche y un irresistible topping de coco rallado.", image: "/images/family-tartas-pizzetas.png" },
];
