export type ProductCategory = "integrales" | "keto";
export type ProductSubcategory = "saladas" | "dulces";


export type Product = {
  id: number;
  name: string;
  category: ProductCategory;
  subcategory: ProductSubcategory;
  price: number;
  isActive?: boolean;
  description: string;
  images: string[];
};

export const PRODUCTS: Product[] = [
  { id: 1, name: "Bases para tartas individuales (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Base para tartas individuales, 100% harina integral: perfecta para tus recetas más saludables. Con una textura crujiente y un sabor suave, es ideal para rellenar con tus ingredientes preferidos. Sin aditivos ni harinas refinadas, esta base es la opción natural para disfrutar de una comida rica y nutritiva. (PRECIO POR 6 UNIDADES)", images: ["/images/Base%20para%20Tartas%20Individuales%20integrales%20-1%20(6).jpg"] },
  { id: 2, name: "Chips (x12)", category: "integrales", subcategory: "saladas", price: 9000, description: "Nuestros chips integrales son perfectos para armar tus sandwiches o disfrutar como quieras. Hechos con harina integral de calidad, vienen en bandejas de 12 unidades listas para acompañar tus comidas o picadas.", images: ["/images/Chips%20Integrales%20(12).png"] },
  { id: 3, name: "Chips rellenos de JyQ (x12)", category: "integrales", subcategory: "saladas", price: 10000, description: "Estos chips integrales son el snack perfecto para cualquier momento del día. Hechos con harina integral, combinan lo mejor del sabor clásico con un toque nutritivo.", images: ["/images/chips-rellenos-jyq-integrales.jpg"] },
  { id: 4, name: "Chips rellenos de caprese (x12)", category: "integrales", subcategory: "saladas", price: 10000, description: "Estos exquisitos chips de harina integral rellenos de caprese te traen todo el sabor mediterráneo en un solo bocado. Con tomate jugoso, albahaca fresca y queso derretido, cada chip es una combinación perfecta de sabores naturales. Vienen en bandeja de 12 Unidades.", images: ["/images/chips-integrales-caprese%20(12).jpg"] },
  { id: 5, name: "Crackers con semillas (250g)", category: "integrales", subcategory: "saladas", price: 6000, description: "Nuestras crackers de harina integral con semillas son el snack perfecto para cualquier momento del día. Hechas con una mezcla de semillas de girasol, sésamo y chía, estos crackers son tan crujientes como nutritivos. Vienen en una bolsa de aproximadamente 250g. Sin conservantes ni harinas refinadas, estas crackers son una opción saludable para acompañar cualquier cosa.", images: ["/images/CRACKERS-INTEGRALES-1.jpeg"] },
  { id: 6, name: "Crutones (250g)", category: "integrales", subcategory: "saladas", price: 4000, description: "Nuestros crutones de harina integral son perfectos para darle ese toque final a tus platos favoritos. Hechos con pan de harina integral, son crujientes y llenos de sabor, ideales para agregar textura a ensaladas, sopas o acompañar tus comidas.", images: ["/images/crutones1.png"] },
  { id: 7, name: "Focaccia con Cherry y Aceituna (grande)", category: "integrales", subcategory: "saladas", price: 9000, description: "Focaccia integral con tomates cherry, aceitunas y especias, perfecta para acompañar o disfrutar sola. ¡Un sabor rústico y delicioso en cada bocado!", images: ["/images/focaccia2.png"] },
  { id: 8, name: "Focaccia con Cherry y Aceituna (chica)", category: "integrales", subcategory: "saladas", price: 6000, description: "Focaccia integral con tomates cherry, aceitunas y especias, perfecta para acompañar o disfrutar sola. ¡Un sabor rústico y delicioso en cada bocado! !También se puede pedir en tamaño grande!", images: ["/images/focaccia.png"] },
  { id: 9, name: "Hamburguesas Legumbres (x6)", category: "integrales", subcategory: "saladas", price: 8500, description: "Elaboradas con ingredientes naturales, nuestras hamburguesas de legumbres vienen en bandejas de 6 unidades y podés elegir entre varios sabores: Lenteja, Garbanzo, Arroz yamaní, Arvejas, Verduras con Arroz yamaní, Soja con Cebolla caramelizada o Calabaza con avena. ¡Una opción nutritiva y deliciosa para cada gusto!", images: ["/images/HAMBURGUESA-LEGUMBRES.png"] },
  { id: 10, name: "Pan de Nuez grande (900g)", category: "integrales", subcategory: "saladas", price: 7000, description: "Nuestro pan de nuez grande es una verdadera delicia casera, hecha con harina integral para ofrecerte un pan nutritivo y lleno de sabor. Con un peso aproximado de 900g , este pan es perfecto para compartir. Su textura rústica y su carga de nueces lo convierten en un pan ideal para acompañar tus comidas, ensaladas, o incluso como snack entre horas.", images: ["/images/pan-nuez-1.jpg", "/images/pan-nuez2.jpg"] },
  { id: 11, name: "Pan Integral grande con semillas (900g)", category: "integrales", subcategory: "saladas", price: 6000, description: "Pan de Molde Horneado. Nuestro pan de molde, elaborado con harina integral y semillas ofrece una miga densa y nutritiva con una corteza dorada. Perfecto para sandwiches o tostadas, cada rebanada combina el sabor auténtico de la harina integral con una textura esponjosa y saludable.", images: ["/images/PAN-INTEGRAL-GRANDE.jpeg"] },
  { id: 12, name: "Pan saborizado chico (x12)", category: "integrales", subcategory: "saladas", price: 8000, description: "Disfrutá estos panes chicos, surtidos con sabores de aceitunas, cebolla, remolacha y queso. Perfectos para picadas o acompañar tus comidas, hechos con ingredientes frescos y un toque casero. ¡Sabores irresistibles en cada bocado!", images: ["/images/Panes%20Saborizados%20Chicos%20(12).jpg"] },
  { id: 13, name: "Pan tortuga mediano (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Una explosión de sabores y colores. Estos panes tortuga vienen en tres variedades: Remolacha, Zapallo y Espinaca. Su miga suave y esponjosa los hace perfectos para acompañar tus picadas o sándwiches. Vienen en bandeja de 6 Unidades.", images: ["/images/Pan%20Tortuga%20Mediano%20(6).jpg"] },
  { id: 14, name: "Pan árabe (x6)", category: "integrales", subcategory: "saladas", price: 8000, description: "Pan Árabe Integral (precio x 6 unidades). Livianos, versátiles y preparados con harina integral. Perfectos para acompañar picadas, rellenar o simplemente disfrutar solos. Saludables y caseros, para cualquier ocasión.", images: ["/images/pan-arabe-integral-1%20(6).jpg"] },
  { id: 15, name: "Pizzetas (x12)", category: "integrales", subcategory: "saladas", price: 12000, description: "Nuestras pre pizzetas de harina integral vienen listas para que las completes a tu gusto. Con una base crujiente y una capa de salsa casera, son la opción perfecta para una comida rápida, saludable y deliciosa. ¡Solo agregá tus ingredientes favoritos y disfrutá!", images: ["/images/PIZZETAS-INTEGRALES.png"] },
  { id: 16, name: "Scones de Queso (x8)", category: "integrales", subcategory: "saladas", price: 6000, description: "Scones de Queso Integrales (bolsa de 6 unidades). Con todo el sabor del queso y hechos con harina integral para que disfrutes sin culpa. ¡Perfectos para acompañar con mate!", images: ["/images/scones-queso1.jpg", "/images/Scones%20de%20Queso-2%20(8).jpg"] },
  { id: 17, name: "Tapa para tacos/fajitas (x6)", category: "integrales", subcategory: "saladas", price: 7000, description: "Nuestras tapas para tacos y fajitas están elaboradas con harina integral, brindando una opción más saludable sin sacrificar el sabor ni la textura. Con 6 unidades por paquete, son suaves, flexibles y perfectas para envolver tus ingredientes favoritos, desde carnes y vegetales hasta combinaciones más creativas.", images: ["/images/fajitas.png"] },
  { id: 18, name: "Tartas individuales", category: "integrales", subcategory: "saladas", price: 6500, description: "Tartas Individuales de harina Integral. Elige entre Calabaza con Choclo y Queso / Jamón y Queso / Cebolla y Queso / Verdura / Caprese / Cebolla Caramelizada / Roquefort. ¡Sabores variados para cada gusto!", images: ["/images/TARTAS-INDIVIDUALES-INTEGRAL.jpg"] },

  { id: 19, name: "Bon o Bon saludable (x4)", category: "integrales", subcategory: "dulces", price: 6500, description: "Bon o Bon saludable sin azúcar, con relleno cremoso y deliciosa cobertura de chocolate. Pack de 4 unidades, ideales para disfrutar sin culpas.", images: ["/images/bonobon.jpg", "/images/bon-o-bon-saludable%284%29.jpg"] },
  { id: 20, name: "Brownie saludable (1 porción)", category: "integrales", subcategory: "dulces", price: 4000, description: "Disfrutá de este brownie saludable, una porción que combina todo el placer del clásico postre con ingredientes más nutritivos. Hecho con harina integral, cacao puro y endulzantes naturales, es perfecto para quienes buscan un capricho dulce sin perder de vista una alimentación equilibrada. Su textura esponjosa y su intenso sabor a chocolate lo convierten en una opción irresistible, ideal para meriendas o postres.", images: ["/images/BROWNIE-PORCION.png"] },
  { id: 21, name: "Budín de Manzana (450g)", category: "integrales", subcategory: "dulces", price: 8000, description: "Budín de Manzana Integral - 450g aprox. Suave, esponjoso y con el dulzor natural de las manzanas. Hecho con harina integral para una opción más sana, perfecto para disfrutar en cualquier momento del día. ¡Una tentación casera y deliciosa!", images: ["/images/budin-manzana1.jpg", "/images/budin-manzana2.jpg"] },
  { id: 22, name: "Carrot Cake", category: "integrales", subcategory: "dulces", price: 8000, description: "Ideamos esta versión saludable del carrot cake para que puedas disfrutar de algo distinto y riquísimo en tus desayunos y meriendas. Hecho con harina integral y endulzado con stevia, es el toque perfecto para endulzar tus momentos sin culpa. ¡No te quedes sin probarlo!", images: ["/images/carrot cake.png"] },
  { id: 23, name: "Muffins de Mandarina (x6)", category: "integrales", subcategory: "dulces", price: 8000, description: "MUFFINS DE MANDARINA. Ideales para una rica merienda saludable! Están hechos con harina integral y nueces, endulzados con stevia. No te los podes perder, son una bomba . Vienen en bandeja de 6 Unidades.", images: ["/images/Muffins%20de%20Mandarina%201%20%286%29.png", "/images/Muffins%20de%20Mandarina%20%286%29.png"] },
  { id: 24, name: "Pancakes (x4)", category: "integrales", subcategory: "dulces", price: 5000, description: "Disfrutá de estos esponjosos pancakes caseros, elaborados con harina integral para una opción más nutritiva. Perfectos para un desayuno energético o una merienda saludable, podés combinarlos con frutas frescas, miel o el topping que más te guste. Vienen en bolsa de 4 Unidades.", images: ["/images/Pancakes%201%20%284%29.jpg", "/images/Pancakes%202%20%284%29.jpg", "/images/Pancakes%20%284%29.jpg"] },
  { id: 25, name: "Pastafrola individual (x1) (Memb./Bat./Ricot.)", category: "integrales", subcategory: "dulces", price: 7000, description: "Pastafrola Individual (Por Unidad) MEMBRILLO - BATATA - RICOTA", images: ["/images/PASTAFROLAS-1.png"] },
  { id: 26, name: "Pepas de Membrillo y Batata (x12)", category: "integrales", subcategory: "dulces", price: 10000, description: "Disfrutá nuestras deliciosas pepas caseras, hechas con harina integral para un toque más saludable. Vienen en una bandeja de 12 unidades, perfectas para compartir o disfrutar en cualquier momento. Rellenas de membrillo y batata, combinan la dulzura con la textura rústica de la harina integral. Ideales para acompañar un buen mate o café.", images: ["/images/Pepas-integrales%20%2812%29.jpg"] },
  { id: 28, name: "Nueces rellenas de DDL bañadas en choc. (x6)", category: "integrales", subcategory: "dulces", price: 7000, description: "Nuestras nueces rellenas con dulce de leche y bañadas en chocolate, todo sin azúcar, son la versión saludable del clásico tentador. Crocantes, bien nueceras y con ese toque de dulce de leche que te hace decir \"¡qué rico esto!\". Un snack ideal para el mate, o cuando pinta el antojo dulce sin salirte de la línea. Vienen de a 6 unidades.", images: ["/images/nueces-ddl-keto-integral.jpg"] },

  { id: 29, name: "Bases para tartas keto (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Conocé nuestra Base para Tarta Keto: la solución ideal. Esta base es crujiente y versátil, perfecta para rellenar con tus sabores favoritos, ya sean dulces o salados. Disfrutá de una opción deliciosa y saludable. Vienen de a 3 o 6 Unidades.", images: ["/images/Base%20para%20Tarta%20Keto%20%283%20o%206%29.jpg"] },
  { id: 30, name: "Bases para tartas keto (x6)", category: "keto", subcategory: "saladas", price: 9000, description: "Conocé nuestra Base para Tarta Keto: la solución ideal. Esta base es crujiente y versátil, perfecta para rellenar con tus sabores favoritos, ya sean dulces o salados. Disfrutá de una opción deliciosa y saludable. Vienen de a 3 o 6 Unidades. (El precio publicado equivale a 6 unidades)", images: ["/images/Base%20para%20Tarta%20Keto%20%283%20o%206%29.jpg"] },
  { id: 31, name: "Chips rellenos de JyQ (x6)", category: "keto", subcategory: "saladas", price: 10000, description: "Disfrutá de estos deliciosos chips Keto rellenos de jamón y queso, hechos con harina de almendras para un toque más saludable. Son perfectos para todo momento. El sabor intenso del jamón y queso se combina con la textura rústica de la harina, creando una explosión de sabor en tu boca. Vienen en bandeja de 12 y también 6 Unidades mas económico.", images: ["/images/family-crackers-chips.png"] },
  { id: 32, name: "Chips rellenos de JyQ (x12)", category: "keto", subcategory: "saladas", price: 15000, description: "Disfrutá de estos deliciosos chips Keto rellenos de jamón y queso, hechos con harina de almendras para un toque más saludable. Son perfectos para todo momento. El sabor intenso del jamón y queso se combina con la textura rústica de la harina, creando una explosión de sabor en tu boca. Vienen en bandeja de 12 y también 6 Unidades mas económico.", images: ["/images/family-crackers-chips.png"] },
  { id: 33, name: "Crackers con semillas (250g)", category: "keto", subcategory: "saladas", price: 7000, description: "Crackers Keto (250g) livianas, crocantes y bajas en carbohidratos. Ideales para picadas saludables y acompañar tus dips favoritos. Una delicia!", images: ["/images/CRACKERS-1.jpg", "/images/CRACKERS-2.jpg"] },
  { id: 34, name: "Tapa/Fajitas para tacos (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Fajitas Keto Ideales para tus tacos, wraps o como acompañamiento. Hechas sin harinas tradicionales, pero cargadas de sabor. Ligeras y flexibles, perfectas para rellenar con tus ingredientes favoritos: carne, pollo, vegetales, ¡Lo que más te guste! Vienen en packs de 3 o 6. El precio publicado corresponde a 6 unidades.", images: ["/images/Tapa-Fajitas%20Keto%20(3%20o%206).jpeg"] },
  { id: 35, name: "Tapa/Fajitas para tacos (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Fajitas Keto Ideales para tus tacos, wraps o como acompañamiento. Hechas sin harinas tradicionales, pero cargadas de sabor. Ligeras y flexibles, perfectas para rellenar con tus ingredientes favoritos: carne, pollo, vegetales, ¡Lo que más te guste! Vienen en packs de 3 o 6. El precio publicado corresponde a 6 unidades.", images: ["/images/Tapa-Fajitas%20Keto%20(3%20o%206).jpeg"] },
  { id: 36, name: "Figacitas (x8)", category: "keto", subcategory: "saladas", price: 9000, description: "Figacitas de Harina de Almendra (bandeja de 8 unidades). Suaves, con ese toque único de la almendra. Perfectas para armar picadas o acompañar tus comidas. Una vuelta de tuerca saludable y sabrosa a las clásicas figacitas.", images: ["/images/FIGACITAS-KETO.jpg"] },
  { id: 37, name: "Muffins de Queso (x6)", category: "keto", subcategory: "saladas", price: 9000, description: "Muffins de queso keto en bandeja de 6, con textura esponjosa y sabor a queso delicioso.", images: ["/images/Muffins%20de%20Queso.jpg"] },
  { id: 38, name: "Pan árabe (x3)", category: "keto", subcategory: "saladas", price: 5000, description: "Pan Árabe Integral (precio x 6 unidades). Livianos, versátiles y preparados con harina integral. Perfectos para acompañar picadas, rellenar o simplemente disfrutar solos. Saludables y caseros, para cualquier ocasión.", images: ["/images/pan-arabe-integral-1%20%286%29.jpg"] },
  { id: 39, name: "Pan árabe (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Pan Árabe Integral (precio x 6 unidades). Livianos, versátiles y preparados con harina integral. Perfectos para acompañar picadas, rellenar o simplemente disfrutar solos. Saludables y caseros, para cualquier ocasión.", images: ["/images/pan-arabe-integral-1%20%286%29.jpg"] },
  { id: 40, name: "Ñoquis Calabaza o Espinaca (500g)", category: "keto", subcategory: "saladas", price: 15000, description: "Ñoquis Keto caseros, bandeja de 500g, disponibles en espinaca o calabaza. Hechos con harina de almendra, sin harinas refinadas. Se cocinan en pocos minutos y podés acompañarlos con la salsa que más te guste.", images: ["/images/ÑOQUIS-500g.jpg"] },
  { id: 41, name: "Pan de Almendras (700g)", category: "keto", subcategory: "saladas", price: 8500, description: "Pan casero horneado, hecho con harina de almendras, perfecto para quienes siguen una dieta Keto. Ligero, nutritivo y sin gluten, con una textura suave que te sorprenderá. Ideal para tus comidas o para acompañar una picada saludable. ¡Una Alternativa deliciosa! (700g aprox.)", images: ["/images/panAlmendras.jpeg"] },
  { id: 42, name: "Pan tortuga (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Nuestro Pan Tortuga Keto es ideal para los que quieren un pancito rico y liviano. Esponjoso, sin gluten, pero con todo el sabor para disfrutar en cualquier momento. Perfecto para hacerte un buen sándwich o acompañar tus comidas. (Bandeja de 6 Unidades)", images: ["/images/pan-tortuga-keto.png"] },
  { id: 43, name: "Pizzetas (x6)", category: "keto", subcategory: "saladas", price: 8500, description: "Pre Pizzetas Keto (bandeja de 6). Con una salsa deliciosa. Ideales para armar tus pizzas sin culpas. Hechas sin harinas tradicionales, son bajas en carbohidratos y perfectas para una comida rápida y saludable. ¡Solo agregá tus toppings favoritos y al horno!", images: ["/images/pizzetas-keto-scaled.jpg"] },
  { id: 44, name: "Scones de Queso (x8)", category: "keto", subcategory: "saladas", price: 7000, description: "Nuestros scones de queso keto son la opción perfecta para quienes buscan un snack delicioso y bajo en carbohidratos. Hechos con harina de almendras y queso de calidad, tienen una textura suave y esponjosa, con el sabor irresistible del queso derretido. Ideales para acompañar el mate, el café o como parte de una picada saludable. ¡Disfrutá sin culpa! (Vienen de a 8 unidades).", images: ["/images/Scons-queso-keto.jpg"] },
  { id: 45, name: "Tartas individuales", category: "keto", subcategory: "saladas", price: 7500, description: "Tartas individuales Keto. Hechas sin harinas tradicionales, estas tartas son ideales para quienes buscan opciones ricas y saludables. Elegí entre nuestras variedades: Calabaza con Choclo y Queso / Jamón y Queso /Cebolla y Queso / Verdura / Caprese / Cebolla Caramelizada / Roquefort. ¡Una opción para cada gusto, perfectas para cualquier ocasión!", images: ["/images/TARTAS-INDIVIDUALES-KETO.jpg"] },

  { id: 46, name: "Alfajor relleno de DDL s/azúcar o ganache de chocolate s/azúcar (x1)", category: "keto", subcategory: "dulces", price: 3500, description: "Alfajor artesanal hecho con harina de almendras, relleno de dulce de leche o ganache. Sabor clásico, sin azúcar. ¡Irresistible y saludable!", images: ["/images/alfajor-relleno-ddl-ganache.jpg", "/images/alfajor-keto-sin-bano-de-chocolate-scaled.jpg"] },
  { id: 47, name: "Alfajor bañado en chocolate relleno de DDL o ganache de chocolate s/azúcar (x1)", category: "keto", subcategory: "dulces", price: 4000, description: "Este alfajor está bañado en chocolate, con un relleno de Dulce de Leche o Ganache de chocolate que se desarma en la boca. Y lo mejor: es sin azúcar y hecho con harina de almendras, así que podés darte el gusto tranqui. Es perfecto para esos momentos donde el antojo te ataca. (Precio por Unidad)", images: ["/images/alfajor-chocolate-ganache-scaled.jpg"] },
  { id: 48, name: "Bombón keto de chocolate relleno de DDL o DDL de arándanos (x6)", category: "keto", subcategory: "dulces", price: 7000, description: "Bombones Keto de chocolate, con un relleno cremoso de Dulce de Leche O Dulce de Leche de Arándanos. Sin azúcar, delicioso, este bombón es perfecto para darte un gusto sin salirte de lo saludable. (Bolsa de 6 Unidades)", images: ["/images/bombon-keto-1-scaled.jpg", "/images/bombon-keto-scaled-2.jpg"] },
  { id: 49, name: "Bon o Bon saludable (x4)", category: "keto", subcategory: "dulces", price: 7000, description: "Bon o Bon saludable sin azúcar, con relleno cremoso y deliciosa cobertura de chocolate. Pack de 4 unidades, ideales para disfrutar sin culpas.", images: ["/images/bonobon.jpg", "/images/bon-o-bon-saludable%284%29.jpg"] },
  { id: 50, name: "Brownie (por porción)", category: "keto", subcategory: "dulces", price: 4500, description: "Disfrutá de este brownie saludable, una porción que combina todo el placer del clásico postre con ingredientes más nutritivos. Hecho con harina integral, cacao puro y endulzantes naturales, es perfecto para quienes buscan un capricho dulce sin perder de vista una alimentación equilibrada. Su textura esponjosa y su intenso sabor a chocolate lo convierten en una opción irresistible, ideal para meriendas o postres.", images: ["/images/BROWNIE-PORCION.png"] },
  { id: 51, name: "Budín con Nuez", category: "keto", subcategory: "dulces", price: 9000, description: "Una opción deliciosa y saludable para tus meriendas o desayunos. Este budín esponjoso está hecho sin harinas tradicionales, con ingredientes Keto, y viene cargado de nueces crocantes que le dan un toque especial. Ideal para darte un gusto sin salirte de la dieta. Sin gluten, sin azúcar y lleno de sabor. ¡Probalo y sorprendete!\"", images: ["/images/BUDIN-CON-NUEZ-KETO-1.jpeg", "/images/BUDIN-CON-NUEZ-KETO.jpeg"] },
  { id: 52, name: "Budín de Limón y Coco (ganache choc. blanco)", category: "keto", subcategory: "dulces", price: 9000, description: "Budín de limón y coco, súper esponjoso, con ese gustito cítrico que te alegra el día. Viene con una ganache de chocolate blanco, es Keto. Perfecto para cuando querés algo rico, pero sin sentirte pesado. Ideal para la merienda!", images: ["/images/budin-de-limon-scaled.jpg"] },
  { id: 53, name: "Mantecol saludable (170g)", category: "keto", subcategory: "dulces", price: 7000, description: "¡Mantecol Saludable que no tiene nada que envidiarle al original! 🎉 Reinventamos el clásico mantecol con una versión saludable y deliciosa de aproximadamente 170 gramos de puro sabor 💣. Elaborado con ingredientes naturales como pasta de maní, frutos secos y chocolate sin azúcar, es la opción perfecta para quienes buscan darse un gusto dulce sin culpas. Aunque igualar el sabor del mantecol tradicional es un desafío, esta versión es igual de irresistible (¡o incluso más!). Probaló y después contanos qué te parece ❤️‍🔥.", images: ["/images/MANTECOL-1.jpg", "/images/MANTECOL-2.jpg", "/images/MANTECOL-3.jpg"] },
  { id: 54, name: "Muffins de Nueces o Arándanos o Chocolate (x6)", category: "keto", subcategory: "dulces", price: 9000, description: "Muffins de Chocolate Keto (bandeja de 6). Deliciosos y esponjosos, hechos sin harinas tradicionales. Ideales para quienes buscan un dulce bajo en carbohidratos, sin perder ese sabor intenso a chocolate que tanto te gusta. Muffins de Arándanos Keto (bandeja de 6). Suaves, frescos y cargados de arándanos. Perfectos para disfrutar en cualquier momento del día, con el equilibrio justo entre lo dulce y lo saludable Muffins de Nueces Keto (bandeja de 6). Elaborados con Harina de Almendras. Cada muffin está lleno de trocitos de nueces que aportan textura y sabor. Perfectos para un snack nutritivo o acompañar un café. ¡Deliciosos!", images: ["/images/muffins-arandanos-1.jpg", "/images/muffins-chocolate-1.jpg", "/images/muffins-chocolate-keto-2.jpg", "/images/muffinNuezKeto.jpg"] },
  { id: 55, name: "Muffins rellenos con ganache (x6)", category: "keto", subcategory: "dulces", price: 9500, description: "Para los amantes del dulce que buscan opciones sin culpa, estos muffins Keto son el placer perfecto. Rellenos con un irresistible ganache cremoso, te ofrecen una delicia baja en carbohidratos pero llena de sabor. Ideales para acompañar el café de la tarde o como postre. Vienen en bandeja de 6 Unidades.", images: ["/images/MUFFINS-REELENO-GANACHE.jpg"] },
  { id: 56, name: "Pancakes (x4)", category: "keto", subcategory: "dulces", price: 7500, description: "Disfrutá de estos esponjosos pancakes caseros, elaborados con harina integral para una opción más nutritiva. Perfectos para un desayuno energético o una merienda saludable, podés combinarlos con frutas frescas, miel o el topping que más te guste. Vienen en bolsa de 4 Unidades.", images: ["/images/Pancakes%201%20%284%29.jpg", "/images/Pancakes%202%20%284%29.jpg", "/images/Pancakes%20%284%29.jpg"] },
  { id: 57, name: "Pan Dulce (350g)", category: "keto", subcategory: "dulces", price: 12000, description: "Disfrutá del clásico pan dulce, pero sin culpa, Keto. Hecho con harinas de almendras, endulzantes naturales y una mezcla irresistible de frutos secos. Ideal para quienes buscan una opción baja en carbohidratos, pero llena de sabor.", images: ["/images/pan-dulce-keto1.jpg", "/images/pan-dulce-keto2.jpg", "/images/pan-dulce-keto3.png"] },
  { id: 58, name: "Pepas de DDL s/azúcar (x12)", category: "keto", subcategory: "dulces", price: 12000, description: "Nuestras Pepas de Dulce de Leche sin Azúcar, irresistibles, están hechas especialmente para quienes siguen un estilo de vida Keto o buscan opciones bajas en carbohidratos. Disfrutá de la suavidad del clásico dulce de leche sin azúcar, acompañado de una masa crocante, libre de harinas refinadas. Vienen en bandeja de 12 unidades.", images: ["/images/pepas-ddl-keto-x12.jpg"] },
  { id: 59, name: "Rogel keto (1200g/1300g)", category: "keto", subcategory: "dulces", price: 35000, description: "Nuestro Rogel Keto es una versión saludable, sin azúcar y apto para quienes siguen una dieta cetogénica. Capas finas y crocantes, intercaladas con un suave dulce de leche sin azúcar y cubierto con un chocolate ligero. Todo el sabor tradicional, sin culpas. (1200g/1300g aprox.)", images: ["/images/rogel-keto1-scaled.jpg", "/images/rogel-keto-scaled.jpg"] },
  { id: 60, name: "Mini rogel tipo alfajor bañado en choco.", category: "keto", subcategory: "dulces", price: 5000, description: "El clásico que amás, en versión mini. Nuestro Mini Rogel keto está hecho con capas crocantes, relleno con dulce de leche sin azúcar y cubierto con un baño de chocolate intenso que se derrite en la boca.", images: ["/images/MINIrogel.jpg"] },
  { id: 61, name: "Mini rogel sin baño", category: "keto", subcategory: "dulces", price: 4500, description: "Mini Rogel Keto Clásico (sin baño) Una delicia en versión saludable. Nuestro Mini Rogel keto mantiene la esencia del postre tradicional, con capas crocantes y ese relleno de dulce de leche sin azúcar que lo hace irresistible… pero sin el baño de chocolate. Ideal para los que prefieren un sabor más suave.", images: ["/images/MINIrogel.jpg"] },
  { id: 62, name: "Tarta de coco individual", category: "keto", subcategory: "dulces", price: 10000, description: "Una delicia que combina lo mejor del coco y el dulce de leche, pero en su versión Keto. Hecha con harina almendras, endulzada con alternativas naturales bajas en carbohidratos, y rellena con dulce de leche sin azúcar. Esta tarta es perfecta para quienes buscan disfrutar de algo dulce sin salir de su estilo de vida keto. Ideal para acompañar un té o sorprender en la sobremesa.", images: ["/images/TARTA-COCO-INDIVIDUAL-KETO.jpg"] },
];




